services:
  postgres:
    image: postgres:16-alpine
    container_name: roomly-postgres
    restart: unless-stopped

    env_file:
      - .env

    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER} 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    
    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - roomly_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

  migrate:
    image: golang:1.26-alpine
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
      GOOSE_MIGRATION_DIR: /app/migrations
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "go install github.com/pressly/goose/v3/cmd/goose@v3.27.3 &&
      goose up"
    restart: "no"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: roomly-api
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
    ports:
      - "${HTTP_PORT}:8080"
    depends_on:
      postgres:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

volumes:
  roomly_postgres_data: