import { FormEvent, ReactNode, useEffect, useMemo, useState } from 'react'
import {
  Bell, Building2, CalendarDays, Check, ChevronLeft, ChevronRight, CircleUserRound,
  Clock3, Edit3, Filter, LayoutDashboard, LogIn, LogOut, Moon, MoreHorizontal, Power,
  Plus, Search, Settings, Sun, Users, X,
} from 'lucide-react'

type Room = { id: string; name: string; location: string; floor?: number; capacity: number; equipment: string[]; is_active: boolean }
type Booking = { id: string; room_id: string; organizer_id?: string; title: string; starts_at: string; ends_at: string; status: 'confirmed' | 'cancelled'; attendees_count: number }
type Claims = { user_id?: string; role?: string }
type ApiError = { message?: string; error?: { message?: string } }
const API_URL = import.meta.env.VITE_API_URL ?? 'http://localhost:8080'
const roomPhotos = ['photo-1497366811353-6870744d04b2', 'photo-1497366754035-f200968a6e72', 'photo-1497366216548-37526070297c', 'photo-1517502884422-41eaead166d4']
const slots = Array.from({ length: 12 }, (_, index) => index + 8)

async function request<T>(path: string, options: RequestInit = {}, token?: string): Promise<T> {
  const response = await fetch(`${API_URL}${path}`, { ...options, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}), ...(options.headers ?? {}) } })
  if (!response.ok) { const body = await response.json().catch(() => ({})) as ApiError; throw new Error(body.message ?? body.error?.message ?? `Ошибка запроса (${response.status})`) }
  return response.json() as Promise<T>
}
function claimsFromToken(token: string): Claims { try { return JSON.parse(atob(token.split('.')[1])) as Claims } catch { return {} } }
function localDateTime(date: Date) { const local = new Date(date.getTime() - date.getTimezoneOffset() * 60000); return local.toISOString().slice(0, 16) }
function formatTime(value: string) { return new Intl.DateTimeFormat('ru-RU', { hour: '2-digit', minute: '2-digit' }).format(new Date(value)) }
function formatDay(value: string) { return new Intl.DateTimeFormat('ru-RU', { weekday: 'short', day: 'numeric', month: 'short' }).format(new Date(value)) }
function initialWindow() { const start = new Date(); start.setMinutes(0, 0, 0); start.setHours(start.getHours() + 1); const end = new Date(start); end.setHours(end.getHours() + 1); return { start: localDateTime(start), end: localDateTime(end) } }

function AppVk() {
  const [token, setToken] = useState(() => localStorage.getItem('roomly_token') ?? '')
  const [authMode, setAuthMode] = useState<'login' | 'register'>('login')
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [fullName, setFullName] = useState(''); const [authError, setAuthError] = useState('')
  if (!token) return <AuthScreen mode={authMode} setMode={setAuthMode} email={email} setEmail={setEmail} password={password} setPassword={setPassword} fullName={fullName} setFullName={setFullName} error={authError} setError={setAuthError} onLogin={setToken} />
  return <Workspace token={token} onLogout={() => { localStorage.removeItem('roomly_token'); setToken('') }} />
}

function AuthScreen({ mode, setMode, email, setEmail, password, setPassword, fullName, setFullName, error, setError, onLogin }: { mode: 'login' | 'register'; setMode: (mode: 'login' | 'register') => void; email: string; setEmail: (value: string) => void; password: string; setPassword: (value: string) => void; fullName: string; setFullName: (value: string) => void; error: string; setError: (value: string) => void; onLogin: (token: string) => void }) {
  const [showPassword, setShowPassword] = useState(false)
  return <main className="vk-auth"><div className="vk-auth-brand"><span className="vk-logo">roomly</span><h1>Переговорные,<br /><span>которые работают.</span></h1><p>Планируйте встречи, смотрите занятость и находите свободное место в несколько кликов.</p></div><form className="vk-auth-card" onSubmit={async (event) => { event.preventDefault(); setError(''); try { if (mode === 'register') { await request('/api/v1/users', { method: 'POST', body: JSON.stringify({ email, password, full_name: fullName }) }); setMode('login'); setError('Аккаунт создан. Войдите с новым паролем.'); return } const result = await request<{ access_token: string }>('/api/v1/auth/login', { method: 'POST', body: JSON.stringify({ email, password }) }); localStorage.setItem('roomly_token', result.access_token); onLogin(result.access_token) } catch (authError) { setError(authError instanceof Error ? authError.message : 'Не удалось выполнить запрос') } }}><div className="vk-auth-heading"><span className="vk-kicker">Roomly ID</span><h2>{mode === 'login' ? 'С возвращением' : 'Создать аккаунт'}</h2></div>{mode === 'register' && <label>Имя<input value={fullName} onChange={(event) => setFullName(event.target.value)} required placeholder="Ваше имя" /></label>}<label>Email<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} required placeholder="you@company.com" /></label><label>Пароль<div className="vk-password"><input type={showPassword ? 'text' : 'password'} minLength={8} value={password} onChange={(event) => setPassword(event.target.value)} required placeholder="Минимум 8 символов" /><button type="button" onClick={() => setShowPassword(!showPassword)} aria-label={showPassword ? 'Скрыть пароль' : 'Показать пароль'}>{showPassword ? 'Скрыть' : 'Показать'}</button></div></label>{error && <p className={error.startsWith('Аккаунт') ? 'vk-success' : 'vk-error'}>{error}</p>}<button className="vk-button primary" type="submit">{mode === 'login' ? 'Войти' : 'Зарегистрироваться'} <LogIn size={18} /></button><button className="vk-text-button" type="button" onClick={() => { setMode(mode === 'login' ? 'register' : 'login'); setError('') }}>{mode === 'login' ? 'Создать новый аккаунт' : 'Уже есть аккаунт'}</button></form></main>
}

function Workspace({ token, onLogout }: { token: string; onLogout: () => void }) {
  const claims = useMemo(() => claimsFromToken(token), [token]); const isAdmin = claims.role === 'admin'
  const [page, setPage] = useState<'dashboard' | 'bookings' | 'admin' | 'settings'>('dashboard'); const [theme, setTheme] = useState<'light' | 'dark'>(() => (localStorage.getItem('roomly_theme') as 'light' | 'dark') ?? (window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light'))
  const [rooms, setRooms] = useState<Room[]>([]); const [bookings, setBookings] = useState<Booking[]>([]); const [loading, setLoading] = useState(true); const [query, setQuery] = useState(''); const [capacity, setCapacity] = useState(''); const [equipment, setEquipment] = useState(''); const [onlyAvailable, setOnlyAvailable] = useState(false); const [modalRoom, setModalRoom] = useState<Room | null>(null); const [toast, setToast] = useState('')
  const windowDefaults = useMemo(initialWindow, []); const [startsAt, setStartsAt] = useState(windowDefaults.start); const [endsAt, setEndsAt] = useState(windowDefaults.end)
  useEffect(() => { document.documentElement.dataset.theme = theme; localStorage.setItem('roomly_theme', theme) }, [theme])
  async function loadData() { setLoading(true); try { const queryParams = new URLSearchParams({ starts_at: new Date(startsAt).toISOString(), ends_at: new Date(endsAt).toISOString() }); const [roomData, bookingData] = await Promise.all([request<Room[]>(`/api/v1/rooms/available?${queryParams}`, {}, token), request<{ items: Booking[] }>(`/api/v1/bookings${claims.user_id ? `?organizer_id=${claims.user_id}` : ''}`, {}, token)]); setRooms(roomData); setBookings(bookingData.items) } catch (error) { setToast(error instanceof Error ? error.message : 'Не удалось загрузить данные') } finally { setLoading(false) } }
  useEffect(() => { void loadData() }, [startsAt, endsAt])
  const filteredRooms = rooms.filter((room) => (!query || `${room.name} ${room.location}`.toLowerCase().includes(query.toLowerCase())) && (!capacity || room.capacity >= Number(capacity)) && (!equipment || room.equipment.some((item) => item.toLowerCase().includes(equipment.toLowerCase()))) && (!onlyAvailable || room.is_active))
  async function cancelBooking(id: string) { try { await request(`/api/v1/bookings/${id}/cancel`, { method: 'POST' }, token); setToast('Бронирование отменено'); await loadData() } catch (error) { setToast(error instanceof Error ? error.message : 'Не удалось отменить бронирование') } }
  const notifications = bookings.filter((booking) => booking.status === 'confirmed' && new Date(booking.ends_at) >= new Date()).sort((left, right) => new Date(left.starts_at).getTime() - new Date(right.starts_at).getTime())
  return <div className="vk-app"><Sidebar page={page} setPage={setPage} isAdmin={isAdmin} onLogout={onLogout} /><div className="vk-main"><Header query={query} setQuery={setQuery} theme={theme} setTheme={setTheme} notifications={notifications} onSwitchProfile={onLogout} /><main className="vk-content">{page === 'dashboard' ? <><div className="vk-page-title"><div><span className="vk-kicker">{new Intl.DateTimeFormat('ru-RU', { weekday: 'long', day: 'numeric', month: 'long' }).format(new Date())}</span><h1>Пространство для встреч</h1><p>Выберите комнату, подходящую вашей команде.</p></div><button className="vk-button primary" onClick={() => setModalRoom(filteredRooms[0] ?? null)}><Plus size={18} /> Новое бронирование</button></div><Filters query={query} setQuery={setQuery} capacity={capacity} setCapacity={setCapacity} equipment={equipment} setEquipment={setEquipment} onlyAvailable={onlyAvailable} setOnlyAvailable={setOnlyAvailable} /><section className="vk-section"><SectionHeader title="Свободные комнаты" count={filteredRooms.length} /><div className="room-cards">{loading ? [1, 2, 3].map((item) => <SkeletonRoom key={item} />) : filteredRooms.map((room, index) => <RoomCard key={room.id} room={room} index={index} onBook={() => setModalRoom(room)} />)}</div>{!loading && filteredRooms.length === 0 && <EmptyState onReset={() => { setQuery(''); setCapacity(''); setEquipment(''); setOnlyAvailable(false) }} />}</section><section className="vk-section"><SectionHeader title="Занятость сегодня" action={<div className="calendar-switch"><button aria-label="Предыдущий день"><ChevronLeft size={17} /></button><strong>Сегодня</strong><button aria-label="Следующий день"><ChevronRight size={17} /></button></div>} /><DayCalendar rooms={rooms} bookings={bookings} onSelect={(room) => setModalRoom(room)} /></section></> : page === 'admin' && isAdmin ? <AdminRoomPanelPage token={token} onToast={setToast} /> : page === 'settings' ? <SettingsPage claims={claims} theme={theme} setTheme={setTheme} /> : <BookingsPage bookings={bookings} rooms={rooms} onCancel={cancelBooking} onBook={() => setModalRoom(rooms[0] ?? null)} />}</main></div>{modalRoom && <BookingModal room={modalRoom} startsAt={startsAt} endsAt={endsAt} setStartsAt={setStartsAt} setEndsAt={setEndsAt} token={token} onClose={() => setModalRoom(null)} onDone={async () => { setModalRoom(null); setToast('Бронирование создано'); await loadData() }} />}{toast && <div className="vk-toast" role="status">{toast}<button onClick={() => setToast('')} aria-label="Закрыть уведомление"><X size={15} /></button></div>}</div>
}

function AdminRoomPanelPage({ token, onToast }: { token: string; onToast: (message: string) => void }) {
  return <><div className="vk-page-title"><div><span className="vk-kicker">Администрирование</span><h1>Управление комнатами</h1><p>Настройте названия, вместимость и доступность переговорных.</p></div><div className="vk-admin-page-mark"><Building2 size={22} /></div></div><AdminRoomPanel token={token} onToast={onToast} /></>
}

function AdminRoomPanel({ token, onToast }: { token: string; onToast: (message: string) => void }) {
  const [rooms, setRooms] = useState<Room[]>([]); const [editingId, setEditingId] = useState<string | null>(null); const [name, setName] = useState(''); const [capacity, setCapacity] = useState(1); const [loading, setLoading] = useState(true)
  async function loadRooms() { try { setRooms(await request<Room[]>('/api/v1/rooms', {}, token)) } catch (error) { onToast(error instanceof Error ? error.message : 'Не удалось загрузить комнаты') } finally { setLoading(false) } }
  useEffect(() => { void loadRooms() }, [])
  async function createRoom(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); try { await request('/api/v1/rooms', { method: 'POST', body: JSON.stringify({ name: form.get('name'), location: form.get('location'), capacity: Number(form.get('capacity')), equipment: String(form.get('equipment') ?? '').split(',').map((item) => item.trim()).filter(Boolean) }) }, token); formElement.reset(); onToast('Комната создана'); await loadRooms() } catch (error) { onToast(error instanceof Error ? error.message : 'Не удалось создать комнату') } }
  async function saveRoom(room: Room) { if (!name.trim() || capacity < 1) { onToast('Название и вместимость обязательны'); return } try { const updated = await request<Room>(`/api/v1/rooms/${room.id}`, { method: 'PATCH', body: JSON.stringify({ name: name.trim(), capacity }) }, token); setRooms((current) => current.map((item) => item.id === updated.id ? updated : item)); setEditingId(null); onToast('Комната обновлена') } catch (error) { onToast(error instanceof Error ? error.message : 'Не удалось обновить комнату') } }
  async function toggleRoom(room: Room) { try { const updated = await request<Room>(`/api/v1/rooms/${room.id}`, { method: 'PATCH', body: JSON.stringify({ is_active: !room.is_active }) }, token); setRooms((current) => current.map((item) => item.id === updated.id ? updated : item)); onToast(updated.is_active ? 'Комната доступна' : 'Комната отключена') } catch (error) { onToast(error instanceof Error ? error.message : 'Не удалось изменить доступность') } }
  return <section className="vk-admin"><SectionHeader title="Управление комнатами" count={rooms.length} /><form className="vk-admin-create" onSubmit={createRoom}><input name="name" required placeholder="Название" /><input name="location" required placeholder="Локация" /><input name="capacity" min="1" required type="number" placeholder="Мест" /><input name="equipment" placeholder="Оборудование" /><button className="vk-button primary" type="submit"><Plus size={16} /> Создать</button></form>{loading ? <div className="vk-admin-loading">Загрузка...</div> : <div className="vk-admin-list">{rooms.map((room) => <div className="vk-admin-row" key={room.id}>{editingId === room.id ? <div className="vk-admin-edit"><input value={name} onChange={(event) => setName(event.target.value)} aria-label="Название комнаты" /><input type="number" min="1" value={capacity} onChange={(event) => setCapacity(Number(event.target.value))} aria-label="Вместимость" /></div> : <div><strong>{room.name}</strong><span>{room.location} · до {room.capacity} мест</span></div>}<div className="vk-admin-actions">{editingId === room.id ? <button className="vk-small-button" onClick={() => { void saveRoom(room) }}><Check size={15} /> Сохранить</button> : <button className="vk-small-button" onClick={() => { setEditingId(room.id); setName(room.name); setCapacity(room.capacity) }}><Edit3 size={15} /> Изменить</button>}<button className={room.is_active ? 'vk-small-button green' : 'vk-small-button'} onClick={() => { void toggleRoom(room) }}><Power size={15} /> {room.is_active ? 'Доступна' : 'Отключена'}</button></div></div>)}</div>}</section>
}

function SettingsPage({ claims, theme, setTheme }: { claims: Claims; theme: 'light' | 'dark'; setTheme: (theme: 'light' | 'dark') => void }) { return <><div className="vk-page-title"><div><span className="vk-kicker">Профиль и предпочтения</span><h1>Настройки</h1><p>Управляйте внешним видом и текущим профилем.</p></div><div className="vk-admin-page-mark"><Settings size={22} /></div></div><section className="vk-settings-grid"><article className="vk-settings-card"><div className="vk-settings-avatar"><CircleUserRound size={30} /></div><div><span className="vk-kicker">Текущий профиль</span><h2>{claims.role === 'admin' ? 'Администратор' : 'Сотрудник'}</h2><p>ID: {claims.user_id ?? 'не определён'}</p></div></article><article className="vk-settings-card"><div><span className="vk-kicker">Оформление</span><h2>Тема интерфейса</h2><p>Выберите светлую или тёмную тему.</p></div><div className="theme-toggle"><button className={theme === 'light' ? 'active' : ''} onClick={() => setTheme('light')}><Sun size={16} /> Светлая</button><button className={theme === 'dark' ? 'active' : ''} onClick={() => setTheme('dark')}><Moon size={16} /> Тёмная</button></div></article></section></> }
function Sidebar({ page, setPage, isAdmin, onLogout }: { page: string; setPage: (page: 'dashboard' | 'bookings' | 'admin' | 'settings') => void; isAdmin: boolean; onLogout: () => void }) { return <aside className="vk-sidebar"><div className="vk-logo">roomly</div><nav><button className={page === 'dashboard' ? 'active' : ''} onClick={() => setPage('dashboard')}><LayoutDashboard size={20} />Обзор</button><button className={page === 'bookings' ? 'active' : ''} onClick={() => setPage('bookings')}><CalendarDays size={20} />Мои бронирования</button>{isAdmin && <button className={page === 'admin' ? 'active' : ''} onClick={() => setPage('admin')}><Building2 size={20} />Управление</button>}</nav><div className="vk-sidebar-bottom"><button className={page === 'settings' ? 'active' : ''} onClick={() => setPage('settings')}><Settings size={20} />Настройки</button><button onClick={onLogout}><LogOut size={20} />Выйти</button></div></aside> }
function Header({ query, setQuery, theme, setTheme, notifications, onSwitchProfile }: { query: string; setQuery: (value: string) => void; theme: 'light' | 'dark'; setTheme: (theme: 'light' | 'dark') => void; notifications: Booking[]; onSwitchProfile: () => void }) { const [notificationsOpen, setNotificationsOpen] = useState(false); const [profileOpen, setProfileOpen] = useState(false); return <header className="vk-header"><div className="vk-search"><Search size={18} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Поиск комнаты или локации" /></div><div className="vk-header-actions"><div className="notification-wrap"><button className="vk-icon-button" onClick={() => setNotificationsOpen(!notificationsOpen)} title="Уведомления" aria-label="Уведомления" aria-expanded={notificationsOpen}><Bell size={19} />{notifications.length > 0 && <b className="notification-badge">{Math.min(notifications.length, 9)}</b>}</button>{notificationsOpen && <div className="notification-popover"><div className="notification-heading"><strong>Уведомления</strong><span>{notifications.length}</span></div>{notifications.length ? notifications.slice(0, 4).map((booking) => <div className="notification-item" key={booking.id}><div className="notification-icon"><CalendarDays size={16} /></div><div><strong>{booking.title}</strong><p>{formatDay(booking.starts_at)} · {formatTime(booking.starts_at)}</p></div></div>) : <div className="notification-empty"><Bell size={20} /><p>Новых уведомлений нет</p></div>}</div>}</div><button className="vk-icon-button" onClick={() => setTheme(theme === 'light' ? 'dark' : 'light')} title="Сменить тему" aria-label="Сменить тему">{theme === 'light' ? <Moon size={19} /> : <Sun size={19} />}</button><div className="profile-wrap"><button className="vk-avatar" onClick={() => setProfileOpen(!profileOpen)} aria-label="Открыть меню профиля" aria-expanded={profileOpen}><CircleUserRound size={20} /></button>{profileOpen && <div className="profile-popover"><strong>Ваш профиль</strong><button onClick={onSwitchProfile}><LogIn size={16} /> Войти в другой профиль</button></div>}</div></div></header> }
function Filters({ query, setQuery, capacity, setCapacity, equipment, setEquipment, onlyAvailable, setOnlyAvailable }: { query: string; setQuery: (value: string) => void; capacity: string; setCapacity: (value: string) => void; equipment: string; setEquipment: (value: string) => void; onlyAvailable: boolean; setOnlyAvailable: (value: boolean) => void }) { return <div className="vk-filters"><div className="filter-label"><Filter size={16} /> Фильтры</div><select value={capacity} onChange={(event) => setCapacity(event.target.value)} aria-label="Вместимость"><option value="">Вместимость</option><option value="4">От 4 мест</option><option value="8">От 8 мест</option><option value="12">От 12 мест</option></select><select value={equipment} onChange={(event) => setEquipment(event.target.value)} aria-label="Оборудование"><option value="">Оборудование</option><option value="ТВ">ТВ</option><option value="доска">Доска</option><option value="видеоконференцсвязь">Видеосвязь</option></select><button className={onlyAvailable ? 'filter-chip active' : 'filter-chip'} onClick={() => setOnlyAvailable(!onlyAvailable)}><Check size={14} /> Доступны сейчас</button><button className="filter-reset" onClick={() => { setQuery(''); setCapacity(''); setEquipment(''); setOnlyAvailable(false) }}>Сбросить</button></div> }
function SectionHeader({ title, count, action }: { title: string; count?: number; action?: ReactNode }) { return <div className="vk-section-header"><div><h2>{title}</h2>{count !== undefined && <span>{count} комнат</span>}</div>{action}</div> }
function RoomCard({ room, index, onBook }: { room: Room; index: number; onBook: () => void }) { return <article className="vk-room-card"><img src={`https://images.unsplash.com/${roomPhotos[index % roomPhotos.length]}?auto=format&fit=crop&w=700&q=80`} alt="" /><div className="vk-room-card-body"><div className="room-card-title"><div><h3>{room.name}</h3><p>{room.location}{room.floor ? ` · ${room.floor} этаж` : ''}</p></div><button className="vk-icon-button" aria-label="Дополнительные действия"><MoreHorizontal size={19} /></button></div><div className="room-meta"><span><Users size={15} /> до {room.capacity}</span>{room.equipment.slice(0, 2).map((item) => <span key={item}>{item}</span>)}</div><div className="availability-line"><span className="availability-dot" /> свободна сейчас</div><button className="vk-button primary full" onClick={onBook}>Забронировать</button></div></article> }
function SkeletonRoom() { return <div className="vk-room-card skeleton-card"><div className="skeleton-block" /><div className="vk-room-card-body"><div className="skeleton-line wide" /><div className="skeleton-line" /><div className="skeleton-line small" /></div></div> }
function EmptyState({ onReset }: { onReset: () => void }) { return <div className="vk-empty"><div className="empty-icon"><Building2 size={28} /></div><h3>Комнаты не найдены</h3><p>Попробуйте изменить фильтры или выбрать другое время.</p><button className="vk-button secondary" onClick={onReset}>Сбросить фильтры</button></div> }
function DayCalendar({ rooms, bookings, onSelect }: { rooms: Room[]; bookings: Booking[]; onSelect: (room: Room) => void }) { return <div className="vk-calendar"><div className="calendar-times"><span />{slots.map((slot) => <span key={slot}>{slot}:00</span>)}</div>{rooms.slice(0, 5).map((room) => <div className="calendar-row" key={room.id}><strong>{room.name}</strong><div className="calendar-track">{slots.map((slot) => { const booking = bookings.find((item) => item.room_id === room.id && new Date(item.starts_at).getHours() <= slot && new Date(item.ends_at).getHours() > slot && item.status === 'confirmed'); return <button key={slot} className={booking ? 'busy' : 'free'} title={booking ? booking.title : 'Свободный слот'} onClick={() => !booking && onSelect(room)} aria-label={`${room.name}, ${slot}:00`}>{booking && slot === new Date(booking.starts_at).getHours() ? booking.title : ''}</button> })}</div></div>)}</div> }
function BookingsPage({ bookings, rooms, onCancel, onBook }: { bookings: Booking[]; rooms: Room[]; onCancel: (id: string) => void; onBook: () => void }) {
  const [tab, setTab] = useState<'upcoming' | 'past'>('upcoming')
  const upcoming = bookings.filter((booking) => booking.status === 'confirmed' && new Date(booking.ends_at) >= new Date())
  const past = bookings.filter((booking) => booking.status === 'cancelled' || new Date(booking.ends_at) < new Date())
  const visibleBookings = tab === 'upcoming' ? upcoming : past

  return <><div className="vk-page-title"><div><span className="vk-kicker">Ваш календарь</span><h1>Мои бронирования</h1><p>Все встречи в одном месте.</p></div><button className="vk-button primary" onClick={onBook}><Plus size={18} /> Новое бронирование</button></div><div className="booking-tabs"><button className={tab === 'upcoming' ? 'active' : ''} onClick={() => setTab('upcoming')}>Предстоящие <b>{upcoming.length}</b></button><button className={tab === 'past' ? 'active' : ''} onClick={() => setTab('past')}>Прошедшие <b>{past.length}</b></button></div><div className="booking-list">{visibleBookings.map((booking) => <article key={booking.id} className="booking-list-item"><div className="booking-date"><strong>{new Date(booking.starts_at).getDate()}</strong><span>{new Intl.DateTimeFormat('ru-RU', { month: 'short' }).format(new Date(booking.starts_at))}</span></div><div><h3>{booking.title}</h3><p><Clock3 size={14} /> {formatDay(booking.starts_at)} · {formatTime(booking.starts_at)}–{formatTime(booking.ends_at)} · {rooms.find((room) => room.id === booking.room_id)?.name ?? 'Комната'}</p></div>{tab === 'upcoming' ? <button className="vk-button secondary" onClick={() => onCancel(booking.id)}>Отменить</button> : <span className="booking-status">{booking.status === 'cancelled' ? 'Отменено' : 'Завершено'}</span>}</article>)}{!visibleBookings.length && <EmptyState onReset={() => undefined} />}</div></>
}
function BookingModal({ room, startsAt, endsAt, setStartsAt, setEndsAt, token, onClose, onDone }: { room: Room; startsAt: string; endsAt: string; setStartsAt: (value: string) => void; setEndsAt: (value: string) => void; token: string; onClose: () => void; onDone: () => Promise<void> }) { const [title, setTitle] = useState(''); const [attendees, setAttendees] = useState(2); const [error, setError] = useState(''); return <div className="vk-modal-overlay" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><form className="vk-modal" onSubmit={async (event) => { event.preventDefault(); setError(''); try { await request('/api/v1/bookings', { method: 'POST', body: JSON.stringify({ room_id: room.id, title, starts_at: new Date(startsAt).toISOString(), ends_at: new Date(endsAt).toISOString(), attendees_count: attendees }) }, token); await onDone() } catch (bookingError) { setError(bookingError instanceof Error ? bookingError.message : 'Не удалось создать бронирование') } }}><div className="modal-heading"><div><span className="vk-kicker">Бронирование</span><h2>{room.name}</h2><p>{room.location} · до {room.capacity} мест</p></div><button type="button" className="vk-icon-button" onClick={onClose} aria-label="Закрыть"><X size={20} /></button></div><label>Тема встречи<input value={title} onChange={(event) => setTitle(event.target.value)} required placeholder="Например, синхронизация команды" /></label><div className="modal-grid"><label>Начало<input type="datetime-local" value={startsAt} onChange={(event) => setStartsAt(event.target.value)} required /></label><label>Окончание<input type="datetime-local" value={endsAt} onChange={(event) => setEndsAt(event.target.value)} required /></label></div><label>Участники<input type="number" min="1" max={room.capacity} value={attendees} onChange={(event) => setAttendees(Number(event.target.value))} required /></label>{error && <p className="vk-error">{error}</p>}<button className="vk-button primary full" type="submit">Подтвердить бронирование</button></form></div> }

export default AppVk
